=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/main/resources/CommandDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Command Descriptor",
  "description": "JSON schema for command descriptors",
  "$ref": "#/definitions/CommandDescriptor",
  "definitions": {
    "CommandDescriptor": {
      "type": "object",
      "properties": {
        "commandName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "topics": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "commandName",
        "description",
        "scope"
      ],
      "additionalProperties": false
    }
  }
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/missingCompatibilityMode/descriptor/test/command/testtestcommand/TestTestCommand.json
{
  "commandName": "TestTestCommand",
  "definingSystem": "TEST",
  "description": "This is a TestCommand",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "TestTestCommand_v1.avdl"
    },
    {
      "version": "2.0.0",
      "valueSchema": "TestTestCommand_v2.avdl"
    },
    {
      "version": "3.0.0",
      "valueSchema": "TestTestCommand_v3.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/sample-message-type-registry/descriptor/jme/command/jmecreatedeclarationcommand/JmeCreateDeclarationCommand.json
{
  "commandName": "JmeCreateDeclarationCommand",
  "definingSystem": "JME",
  "description": "Initiate the creation of a customs declaration.",
  "documentationUrl": "https://testhost",
  "topic": "jme-messaging-create-declaration",
  "topics": [
    "additional-topic"
  ],
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "JmeCreateDeclarationCommand_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.1.0",
      "valueSchema": "JmeCreateDeclarationCommand_v1.1.0.avdl",
      "keySchema": "JmeCreateDeclarationCommand_key_v1.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/sample-message-type-registry/descriptor/wvs/command/wvscreatedeclarationcommand/WvsCreateDeclarationCommand.json
{
  "commandName": "WvsCreateDeclarationCommand",
  "definingSystem": "WVS",
  "description": "Initiate the creation of a customs declaration.",
  "documentationUrl": "https://testhost",
  "topic": "wvs-messaging-create-declaration",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "WvsCreateDeclarationCommand_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/test-registry/commit-3/descriptor/autorisaziun/command/autorisaziuncancelpermitconsumptioncommand/AutorisaziunCancelPermitConsumptionCommand.json
{
  "commandName": "AutorisaziunCancelPermitConsumptionCommand",
  "definingSystem": "AUTORISAZIUN",
  "description": "Command that is issued by a system to cancel a permit consumption",
  "documentationUrl": "https://test",
  "topic": "autorisaziun-cancel-permitconsumption",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "AutorisaziunCancelPermitConsumptionCommand_v1.0.0.avdl",
      "compatibilityMode": "NONE"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/validCommandMinorVersionUpdate/descriptor/test/command/testtestcommand/TestTestCommand.json
{
  "commandName": "TestTestCommand",
  "definingSystem": "TEST",
  "description": "This is a TestCommand",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.2.0",
      "valueSchema": "TestTestCommand_v1.2.0.avdl"
    },
    {
      "version": "1.3.0",
      "valueSchema": "TestTestCommand_v1.3.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}
