=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/main/resources/EventDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Event Descriptor",
  "description": "JSON schema for event descriptors",
  "$ref": "#/definitions/EventDescriptor",
  "definitions": {
    "EventDescriptor": {
      "type": "object",
      "properties": {
        "eventName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "publishingSystem": {
          "type": "string",
          "minLength": 2,
          "$comment": "deprecated - use definingSystem"
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "topics": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "eventName",
        "description",
        "scope"
      ],
      "anyOf": [
        {
          "required": [
            "publishingSystem"
          ]
        },
        {
          "required": [
            "definingSystem"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/messageTypeNameMissingInSchema/descriptor/autorisaziun/event/autorisaziunpermitvalidationdeclinedevent/AutorisaziunPermitValidationDeclinedEvent.json
{
  "eventName": "AutorisaziunPermitValidationDeclinedEvent",
  "definingSystem": "AUTORISAZIUN",
  "description": "Event that is published by Autorisaziun when a permit validation was declined",
  "documentationUrl": "https://test",
  "topic": "autorisaziun-permitvalidation-declined",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "AutorisaziunPermitValidationDeclinedEvent_v1.0.0.avdl"
    },
    {
      "version": "1.1.0",
      "valueSchema": "AutorisaziunPermitValidationDeclinedEvent_v1.1.0.avdl",
      "compatibilityMode": "NONE"
    },
    {
      "version": "2.0.0",
      "valueSchema": "AutorisaziunPermitValidationDeclinedEvent_v2.0.0.avdl",
      "compatibilityMode": "NONE"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/test-registry/commit-1/descriptor/activ/event/activzoneenteredevent/ActivZoneEnteredEvent.json
{
  "eventName": "ActivZoneEnteredEvent",
  "description": "Device entered in activation zone.",
  "publishingSystem": "ACTIV",
  "scope": "public",
  "topic": "activ-activation-zoneentered",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "ActivZoneEnteredEvent_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/validMultipleTopics/descriptor/test/event/testtestevent/TestTestEvent.json
{
  "eventName": "TestTestEvent",
  "definingSystem": "TEST",
  "description": "This is a test event",
  "documentationUrl": "http://example.com",
  "topics": [
    "topic-1",
    "topic-2"
  ],
  "scope": "public",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "TestTestEvent_v1.avdl",
      "keySchema": "TestTestEvent_key_v1.avdl"
    }
  ]
}
