=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/main/resources/EventDescriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Event Descriptor",
  "description": "JSON schema for event descriptors",
  "$ref": "#/definitions/EventDescriptor",
  "definitions": {
    "EventDescriptor": {
      "type": "object",
      "properties": {
        "eventName": {
          "type": "string",
          "minLength": 10
        },
        "definingSystem": {
          "type": "string",
          "minLength": 2
        },
        "publishingSystem": {
          "type": "string",
          "minLength": 2,
          "$comment": "deprecated - use definingSystem"
        },
        "description": {
          "type": "string"
        },
        "documentationUrl": {
          "$ref": "common.schema.json#/definitions/url"
        },
        "scope": {
          "type": "string",
          "enum": [
            "public",
            "internal"
          ]
        },
        "topic": {
          "type": "string"
        },
        "topics": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "versions": {
          "$ref": "common.schema.json#/definitions/Versions"
        }
      },
      "required": [
        "eventName",
        "description",
        "scope"
      ],
      "anyOf": [
        {
          "required": [
            "publishingSystem"
          ]
        },
        {
          "required": [
            "definingSystem"
          ]
        }
      ],
      "additionalProperties": false
    }
  }
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/commonData/descriptor/test/event/testtestevent/TestTestEvent.json
{
  "eventName": "TestTestEvent",
  "definingSystem": "TEST",
  "description": "This is a test event",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "TestTestEvent_v1.1.0.avdl",
      "keySchema": "ch.admin.bit.jeap.domainevent.registry.verifier.testevent.TestTestEventKey.avdl"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/valid/descriptor/test/event/testtestevent/TestTestEvent.json
{
  "eventName": "TestTestEvent",
  "definingSystem": "TEST",
  "description": "This is a test event",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "TestTestEvent_v1.avdl",
      "keySchema": "TestTestEvent_key_v1.avdl"
    },
    {
      "version": "1.2.0",
      "valueSchema": "TestTestEvent_v2.avdl",
      "keySchema": "TestTestEvent_key_v1.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.3.0",
      "valueSchema": "TestTestEvent_v3.avdl",
      "keySchema": "TestTestEvent_key_v1.avdl",
      "compatibilityMode": "BACKWARD",
      "compatibleVersion": "1.1.0"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/compatibleChange/descriptor/test/event/testsingleversionevent/TestSingleversionEvent.json
{
  "eventName": "TestSingleversionEvent",
  "definingSystem": "TEST",
  "description": "This is a test event",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "TestSingleversionEvent_v1.0.0.avdl"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/danglingFile/descriptor/test/event/testtestevent/TestTestEvent.json
{
  "eventName": "TestTestEvent",
  "definingSystem": "TEST",
  "description": "This is a test event",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "TestTestEvent_v1.avdl",
      "keySchema": "TestTestEvent_key_v1.avdl"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/sample-message-type-registry-custom-pom/descriptor/jme/event/jmedeclarationcreatedevent/JmeDeclarationCreatedEvent.json
{
  "eventName": "JmeDeclarationCreatedEvent",
  "publishingSystem": "JME",
  "description": "Customs declaration created event",
  "documentationUrl": "https://testhost",
  "topic": "jme-messaging-declaration-created",
  "topics": [
    "additional-topic"
  ],
  "scope": "internal",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v1.1.0.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-registry-maven-plugin/src/test/resources/compatibleChange/descriptor/test/event/testtestevent/TestTestEvent.json
{
  "eventName": "TestTestEvent",
  "definingSystem": "TEST",
  "description": "This is a test event",
  "documentationUrl": "http://example.com",
  "topic": "test-test",
  "scope": "public",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "TestTestEvent_v1.avdl"
    },
    {
      "version": "1.2.0",
      "valueSchema": "TestTestEvent_v2.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.3.0",
      "valueSchema": "TestTestEvent_v3.avdl",
      "compatibilityMode": "BACKWARD",
      "compatibleVersion": "1.1.0"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/sample-message-type-registry/descriptor/jme/event/jmedeclarationcreatedevent/JmeDeclarationCreatedEvent.json
{
  "eventName": "JmeDeclarationCreatedEvent",
  "publishingSystem": "JME",
  "description": "Customs declaration created event",
  "documentationUrl": "https://testhost",
  "topic": "jme-messaging-declaration-created",
  "topics": [
    "additional-topic"
  ],
  "scope": "internal",
  "versions": [
    {
      "version": "1.1.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v1.avdl",
      "keySchema": "JmeDeclarationCreatedEvent_key_v1.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.2.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v2.avdl",
      "keySchema": "JmeDeclarationCreatedEvent_key_v2.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.3.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v3.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "1.4.0",
      "valueSchema": "JmeDeclarationCreatedEvent_v4.avdl",
      "keySchema": "ch.admin.bit.jme.declaration.BeanReferenceMessageKey.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}

=== jeap-admin-ch/jeap-messaging/jeap-messaging-avro-maven-plugin/src/test/resources/test-registry/commit-2/descriptor/activ/event/activzoneenteredevent/ActivZoneEnteredEvent.json
{
  "eventName": "ActivZoneEnteredEvent",
  "description": "Device entered in activation zone.",
  "publishingSystem": "ACTIV",
  "scope": "public",
  "topic": "activ-activation-zoneentered",
  "versions": [
    {
      "version": "1.0.0",
      "valueSchema": "ActivZoneEnteredEvent_v1.0.0.avdl",
      "compatibilityMode": "BACKWARD"
    },
    {
      "version": "2.0.0",
      "valueSchema": "ActivZoneEnteredEvent_v2.0.0.avdl",
      "keySchema": "ch.admin.bazg.activ.test.event.v2.SystemCommon.avdl",
      "compatibilityMode": "BACKWARD"
    }
  ]
}
